#### template file for use with pattern-container1.mks, [GnumakeUniproc v1.0]
# ! Be sure to replace every occurrence of <angle-brackets> to be your
# actual content, or [ at least comment them out if some of them are
# not required] .

gmu_PRJ_NAME = <project-name-for-this-container>

#gmp_CONTAINER_EXTRACT_COMPILER_ID = 1 
	# Do not define this since we do not do GMU style compile, 
	# and there is no sub-project to use it.

# Replace <your-custom-target> with you own make-target whose rule should
# appear in u_freestyle.mki .
gmu_DELIBERATE_NO_SUBPRJ = 1 
gmp_USER_FIRST_TARGET = <your-custom-target>


include $(gmu_DIR_GNUMAKEUNIPROC)/pattern-container1.mks

