#### template file for use with pattern1-container.mks, [GnumakeUniproc v1.0]
# ! Be sure to replace every occurrence of <angle-brackets> to be your
# actual content, or [ at least comment them out if some of them are
# not required] .

gmu_PRJ_NAME = itclr-cntr-one

#gmp_CONTAINER_EXTRACT_COMPILER_ID = 1 
	# Do not define this since we do not need gmp_COMPILER_ID 
	# for sub-project's attributes .

include $(gmu_DIR_GNUMAKEUNIPROC)/pattern1-container.mks

