@echo off
set gmu_DIR_ROOT_bs=%~dp0
set gmu_DIR_ROOT_bs=%gmu_DIR_ROOT_bs:~0,-1%
	:Note: We NEED _gmu_DIR_ROOT_bs in latter part(auto generated by GMU instaler)
set gmu_DIR_ROOT=%gmu_DIR_ROOT_bs:\=/%

:If full path of this .bat is D:\some\path\gmuenv.bat, resulting gmu_DIR_ROOT=D:/some/path
:More env-vars below are appended by GMU installer
