#!/bin/bash

source $(dirname $0)/gmu-share.sc # get gmu_rel2abs_path()

tmpbatdir=$(realpath ${0%/*} 2>/dev/null) || tmpbatdir=$(gmu_rel2abs_path ${0%/*})

export gmu_DIR_ROOT=${tmpbatdir%/GMU-main/umake_cmd/bashcmd}


source $gmu_DIR_ROOT/_gmuenv.sc

################### some vars and functions for convenience ###################

# lset: Find exported env-vars whose names start with specific leading words
# Example:
#	$ lset gmu
#	gmu_LOG_OUTPUT_FILENAME=_gmulog.txt
#	gmu_DIR_ROOT=/home/chj/w/GMU
#	gmu_SUPPRESS_INCLUDE_NOT_FOUND_WARNING=1
#	gmu_MAKE_EXE=gmu-make
#	gmu_DO_SHOW_LINK_CMD=1
#	gmu_DIR_GNUMAKEUNIPROC=/home/chj/w/GMU/GMU-main/GnumakeUniproc
#	gmu_ver=0.99
# like a super Windows CMD 'set', so I name it "linux set".
lset(){
	for v in "$@"; do
		env | grep "^$v"
	done
}

lgmv(){
	lset gmu_
	lset gmp_
	lset gmi_
	lset gms_
	env | grep "^gv[0-9]"
}
# Note: I do not use one single regex because I would not be able to have gmu_ before gmp_ .

lgmv
