
gmp_up_WINDLL_MODULE_DEF_FROM_ROOT = zlib.def

gmp_mswin_IMPLIB_SUFFIX = --imp

gmp_u_list_PLUGIN_TO_LOAD += PI_winres_msvc

# PI_winres_msvc vars:
gmi_RCVC_up_list_WINRC_FROM_ROOT = zlib1.rc

include ../dll.mki
