#### template file for use with pattern1-container.mks, [GnumakeUniproc v1.0]
# ! Be sure to replace every occurrence of <angle-brackets> to be your
# actual content, or [ at least comment them out if some of them are
# not required] .

gmu_PRJ_NAME = gmuex-MakeSDK2

include $(gmu_DIR_GNUMAKEUNIPROC)/pattern1-container.mks

