#compiler-settings
cheetahVarStartToken = @
#end compiler-settings

ifdef gmu_DIR_ROOT
  include $(gmu_DIR_ROOT)/nlscan/nlssvn-scalacon.mki
else
  $(error gmu_DIR_ROOT is not defined, You have to set up GnumakeUniproc environment to use this Makefile)
endif

ifndef gmb_syncto
  gmb_syncto = $(CURDIR)/nlssdk
endif

gmu_PRJ_NAME = @(repo).LinuxgccSdk

gmp_COMPILER_ID=
	# immune to environment gmp_COMPILER_ID inheritance 

gmp_USER_POST_TARGETS += # <some make targets>
	# If you'd like something to be done after all sub-projects is built, 
	# you can list your targets in this var, and executes your commands under
	# these targets.

gmp_u_list_PLUGIN_TO_LOAD += PI_makesdk_2011
  gmi_MSDK1_up_BUILDSDK_INI = buildsdk.ini


include $(gmu_DIR_GNUMAKEUNIPROC)/pattern1-container.mks

