ifndef gmu_PRJ_NAME
  gmu_PRJ_NAME = itclr-libC
	# itclr: Internal Test Cross Lib Ref
endif

ifndef gmp_bc_IMAGE_TYPE
  gmp_bc_IMAGE_TYPE = LIB
endif

gmp_u_list_PLUGIN_TO_LOAD += 
	# PI_sync_devoutput PI_always_compile

include $(gmu_DIR_GNUMAKEUNIPROC)/pattern1.mks

