gmu_up_list_SRC_FROM_ROOT += mswin/walkdir.c mswin/ps_func.c

gmp_bc_CRT_STATIC_LIB = 1
	# 1: Use static CRT lib (compiler option /MT or /MTd)
	# (null): use DLL CRT lib (compiler option /MD or /MDd)

include ../lib.mki
